# URL
baseurl: "/iit-qc-workshop" # the subpath of your site, e.g. /blog
url: "pedrorrivero.github.io" # the base hostname & protocol for your site

# Info
title: IIT QC Workshop
date: April 30th, 2021
location: Online
description: > # this means to ignore newlines until "registration:"
  Your description
registration:
  deadline: April 30, 2021
  url: https://docs.google.com/forms/d/e/1FAIpQLScf_uY-qCdlRvuJNC6zu89Uw76oy9VBfbpTacAZGDeVVO7cVw/viewform?embedded=true
  embedded: true # Embed form (in google-form: ?embedded=true)

# Theme
colors:
  primary: '#BB271A'
  secondary: '#EA3223'
  section: '#FF805B'
  navbar: '#222'
  text: '#00283C'
  muted: '#777'
font:
  primary: 'Montserrat, "Helvetica Neue",Helvetica,Arial,sans-serif'
  secondary: '"Droid Serif", "Helvetica Neue", Helvetica,Arial,sans-serif'

# Build settings
markdown: kramdown
timezone: America/Chicago

include:
  - _server
  - .htaccess
exclude:
  - README.md
  - LICENSE
  - _pages/booklet.html
  - _pages/venue.html

defaults:
  - scope:
      path: _server
    values:
      permalink: /:basename
  - scope:
      path: _public
    values:
      sitemap: false

collections:
  pages:
    output: true
    permalink: /:name
  public:
    output: true
    permalink: /:path

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


# social:
#   name: Your Facebook Page
#   link: "https://www.facebook.com/"

# google_site_verification: googleXXXXXXXXXXXXXXXX.html
# facebook:
#   app_id:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: facebook
#     url: https://www.facebook.com
#   - title: twitter
#     url: https://twitter.com
