# Meta
title: IIT QC Workshop
description: > # this means to ignore newlines until "baseurl:"
  Your description

# URL
baseurl: "/iit-qc-workshop" # the subpath of your site, e.g. /blog
url: "pedrorrivero.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
timezone: America/Chicago

include:
  - _server
  - .htaccess

exclude:
  - README.md
  - LICENSE

defaults:
  - scope:
      path: _server
    values:
      permalink: /:basename
  - scope:
      path: _public
    values:
      sitemap: false

collections:
  pages:
    output: true
    permalink: /:name
  public:
    output: true
    permalink: /:path

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# social:
#   name: Your Facebook Page
#   link: "https://www.facebook.com/"

# google_site_verification: googleXXXXXXXXXXXXXXXX.html
# facebook:
#   app_id:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: facebook
#     url: https://www.facebook.com
#   - title: twitter
#     url: https://twitter.com
