title: IIT QC Workshop
description: > # this means to ignore newlines until "baseurl:"
  Your description
baseurl: "/iit-qc-workshop" # the subpath of your site, e.g. /blog
url: "pedrorrivero.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

logo: "/public/img/TBD.jpg"

include:
  - .htaccess
  - _pages

exclude:
  - README.md
  - LICENSE

defaults:
  - scope:
      path: _pages
    values:
      permalink: /:basename

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# social:
#   name: Your Facebook Page
#   link: "https://www.facebook.com/"

# google_site_verification: googleXXXXXXXXXXXXXXXX.html
# facebook:
#   app_id:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: facebook
#     url: https://www.facebook.com
#   - title: twitter
#     url: https://twitter.com
