name: Jekyll site scheduled build

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    name: Build Jekyll site
    runs-on: ubuntu-latest

    steps:
    - name: Github pages build API request
      run: |
        curl \
        -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ secrets.GH_OAUTH_TOKEN }}" \
        https://api.github.com/repos/${{ github.repository }}/pages/builds
